version: 2.1

orbs:
  ruby: circleci/ruby@1.0

jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.7.2'
    steps:
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: 'cimg/ruby:2.7.2'
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      - run:
          name: Lint
          command: bundle exec rake standard

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
